// app/layout.tsx
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar";

// Load Geist fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Load ElevonTwoG font
const elevonTwoG = localFont({
  src: "./fonts/ElevonTwoG.ttf",
  variable: "--font-elevon-two-g",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${elevonTwoG.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
